"""initial schema

Revision ID: 60c54ecc505b
Revises: 
Create Date: 2026-07-04 15:58:46.451370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60c54ecc505b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('repoPath', sa.Text(), nullable=False),
    sa.Column('sortOrder', sa.Float(), nullable=False),
    sa.Column('createdAt', sa.Integer(), nullable=False),
    sa.Column('updatedAt', sa.Integer(), nullable=False),
    sa.CheckConstraint("type IN ('work', 'argonath')", name='ck_project_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scratchpads',
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.Integer(), nullable=False),
    sa.Column('updatedAt', sa.Integer(), nullable=False),
    sa.CheckConstraint("type IN ('work', 'argonath')", name='ck_scratchpad_type'),
    sa.PrimaryKeyConstraint('type')
    )
    op.create_table('releases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('projectId', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('startDate', sa.Integer(), nullable=True),
    sa.Column('endDate', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('sortOrder', sa.Float(), nullable=False),
    sa.Column('createdAt', sa.Integer(), nullable=False),
    sa.Column('updatedAt', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('projectId', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('filesAffected', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('subitems', sa.Text(), nullable=True),
    sa.Column('sortOrder', sa.Float(), nullable=False),
    sa.Column('completedAt', sa.Integer(), nullable=True),
    sa.Column('releaseId', sa.String(), nullable=True),
    sa.Column('createdAt', sa.Integer(), nullable=False),
    sa.Column('updatedAt', sa.Integer(), nullable=False),
    sa.CheckConstraint("state IN ('BACKLOG', 'TODO', 'ONGOING', 'DONE')", name='ck_item_state'),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['releaseId'], ['releases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('projectId', sa.String(), nullable=True),
    sa.Column('releaseId', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.Integer(), nullable=False),
    sa.Column('updatedAt', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['releaseId'], ['releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    op.drop_table('items')
    op.drop_table('releases')
    op.drop_table('scratchpads')
    op.drop_table('projects')
    # ### end Alembic commands ###
